// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmid6qA5TjNlB_vom9AdIkCN-qyI50qTI',
    appId: '1:915122254901:web:4cfa814cd2e0f5177d2d7c',
    messagingSenderId: '915122254901',
    projectId: 'ciu-study-mate',
    authDomain: 'ciu-study-mate.firebaseapp.com',
    storageBucket: 'ciu-study-mate.appspot.com',
    measurementId: 'G-CZQ2TTHFS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfubfxv3FKa6HDZUawJwlp3yquYqyKgxU',
    appId: '1:915122254901:android:5537e2639faf05e87d2d7c',
    messagingSenderId: '915122254901',
    projectId: 'ciu-study-mate',
    storageBucket: 'ciu-study-mate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb0A10qA7Q6vfUSbHBOa145w5sZ0po9gQ',
    appId: '1:915122254901:ios:8aa4c2d2e2643e977d2d7c',
    messagingSenderId: '915122254901',
    projectId: 'ciu-study-mate',
    storageBucket: 'ciu-study-mate.appspot.com',
    iosBundleId: 'com.example.studyMateWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb0A10qA7Q6vfUSbHBOa145w5sZ0po9gQ',
    appId: '1:915122254901:ios:8aa4c2d2e2643e977d2d7c',
    messagingSenderId: '915122254901',
    projectId: 'ciu-study-mate',
    storageBucket: 'ciu-study-mate.appspot.com',
    iosBundleId: 'com.example.studyMateWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmid6qA5TjNlB_vom9AdIkCN-qyI50qTI',
    appId: '1:915122254901:web:2a3ec46426d4bcb77d2d7c',
    messagingSenderId: '915122254901',
    projectId: 'ciu-study-mate',
    authDomain: 'ciu-study-mate.firebaseapp.com',
    storageBucket: 'ciu-study-mate.appspot.com',
    measurementId: 'G-M761DRPHYN',
  );
}
